# Generated by Django 2.2.4 on 2020-04-19 12:08

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('reports', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=10)),
                ('TL', models.CharField(choices=[('Raktima Mitra', 'Raktima Mitra'), ('Akansha', 'Akansha'), ('Amitesh Ranjan', 'Amitesh Ranjan'), ('Shekhar', 'Shekhar'), ('Ajeet', 'Ajeet'), ('Sheetal', 'Sheetal'), ('Kanika', 'Kanika')], max_length=20)),
                ('No_hours', models.IntegerField()),
                ('progress', models.CharField(max_length=200)),
                ('Dtoday', models.FileField(upload_to=report.models.get_upload_path)),
                ('concern', models.CharField(max_length=200)),
                ('Nextplan', models.CharField(max_length=200)),
                ('Dnextp', models.FileField(upload_to=report.models.next_upload_path)),
            ],
        ),
    ]
