# Generated by Django 2.2.4 on 2020-04-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200419_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Dnextp',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Dtoday',
        ),
        migrations.AddField(
            model_name='report',
            name='TL',
            field=models.CharField(choices=[('Raktima Mitra', 'Raktima Mitra'), ('Akansha', 'Akansha'), ('Amitesh Ranjan', 'Amitesh Ranjan'), ('Shekhar', 'Shekhar'), ('Ajeet', 'Ajeet'), ('Sheetal', 'Sheetal'), ('Kanika', 'Kanika')], default='Kanika', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='reports',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=10),
        ),
    ]
