# Generated by Django 2.2.4 on 2020-04-19 13:06

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20200419_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
        migrations.AddField(
            model_name='report',
            name='Dnextp',
            field=models.FileField(null=True, upload_to=report.models.next_upload_path),
        ),
        migrations.AddField(
            model_name='report',
            name='Dtoday',
            field=models.FileField(null=True, upload_to=report.models.get_upload_path),
        ),
    ]
