# Generated by Django 2.2.4 on 2020-04-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
