# Generated by Django 2.2.4 on 2020-04-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20200419_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Nextplan',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='concern',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
